language: node_js
node_js:
  - "iojs"
  - "node"
  - "0.12"
  - "0.11"
  - "0.10"
sudo: false

before_script:
  - npm install -g mocha

script: npm run coverage

after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha test/test.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
