language: node_js
node_js:
  - "iojs"
  - "node"
  - "0.12"
  - "0.11"
  - "0.10"
sudo: false

before_script:
  - npm install -g mocha

script: npm run coverage

after_script: 
- ./node_modules/karma/bin/karma start
- istanbul cover ./node_modules/mocha/bin/_mocha server/api/**/*.spec.js
- cat ./coverage/lcov.info ./coverage/karma/**/*.info > lcov.info 
- node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
